export enum TableName {
  users = 'users',
  studios = 'studios',
  studioUsers = 'studio_users',
  studioPhotos = 'studio_photos',
  spaces = 'spaces',
  spaceUsers = 'space_users',
  spacePhotos = 'space_photos',
  bookings = 'bookings',
  bookingItems = 'booking_items',
  bookingReviews = 'booking_reviews',
  bookingPayments = 'booking_payments',
  settings = 'settings',
  services = 'services',
}
